#!/system/bin/sh
# Partition Optimizer fstrim
#Interval between Fstrim runs, in seconds, 2592000 = 1Month
# 604800 = 1Week
RUN_EVERY=604800

LOG=/data/.hybridmax/fstrim.log

busybox rm -f $LOG
busybox touch $LOG

echo "fstrim started at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG;

fstrim -v /cache | tee -a $LOG;
fstrim -v /data | tee -a $LOG;
fstrim -v /system | tee -a $LOG
fstrim -v /preload | tee -a $LOG

echo "fstrim finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG;
